### ISSUE TITLE
Autocomplete for MetricsQL

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/vmui#16]
need to add autocomplete for MetricQL subset
if this is required some additional func from backend please let me know :)

**Comment by valyala** [comment]
FYI, vmui source code has been embedded into VictoriaMetrics - see [this issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1413), so further development should take place at https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/app/vmui .

Closing this issue. Feel free re-creating it at [the main VictoriaMetrics repository](https://github.com/VictoriaMetrics/VictoriaMetrics/issues).

P.S. I'm not sure this feature request is needed, since autocomplete is useless and distracting in most cases. I'd rather remove the existing auto-completion from the `vmui` embedded into VictoriaMetrics.
